import {
  adminCreateUserSchema,
  adminTeamCreateSchema,
  adminTeamUpdateSchema,
  adminUpdateUserSchema,
} from "../validation/schemas.js";
import { noContent, notFound, type Operation, ok } from "./operation.js";

/** The admin API: accounts, teams, the audit log, the update check and the
 * setup checks. */
export const ADMIN_OPERATIONS: Operation[] = [
  {
    method: "get",
    path: "/api/admin/teams",
    tag: "Admin",
    summary: "Every team, with its members",
    auth: "admin",
    feature: "teams",
    limits: ["user"],
    responses: ok("AdminTeamsResponse"),
  },
  {
    method: "post",
    path: "/api/admin/teams",
    tag: "Admin",
    summary: "Make a team, optionally with members",
    auth: "admin",
    feature: "teams",
    limits: ["user"],
    body: adminTeamCreateSchema,
    responses: {
      "201": { description: "Made", schema: "AdminTeamResponse" },
      "409": { description: "The name is taken", schema: "Error" },
    },
  },
  {
    method: "put",
    path: "/api/admin/teams/:id",
    tag: "Admin",
    summary:
      "Rename a team or set its members; a team from the identity provider is refused",
    auth: "admin",
    feature: "teams",
    limits: ["user"],
    body: adminTeamUpdateSchema,
    responses: { ...ok("AdminTeamResponse"), ...notFound },
  },
  {
    method: "delete",
    path: "/api/admin/teams/:id",
    tag: "Admin",
    summary: "Remove a team, and the notes that came through it",
    auth: "admin",
    feature: "teams",
    limits: ["user"],
    responses: { ...noContent, ...notFound },
  },
  {
    method: "get",
    path: "/api/admin/users",
    tag: "Admin",
    summary: "Every account",
    auth: "admin",
    limits: ["user"],
    responses: ok("AdminUsersResponse"),
  },
  {
    method: "get",
    path: "/api/admin/users/:id/export",
    tag: "Admin",
    summary: "Every note an account owns, as a zip (only with ADMIN_EXPORT on)",
    auth: "admin",
    feature: "adminExport",
    limits: ["user"],
    responses: { "200": { description: "application/zip" }, ...notFound },
  },
  {
    method: "get",
    path: "/api/admin/update",
    tag: "Admin",
    summary: "The running version, and the newest release if the check is on",
    auth: "admin",
    limits: ["user"],
    responses: ok(),
  },
  {
    method: "get",
    path: "/api/admin/overview",
    tag: "Admin",
    summary: "What the server holds, and how its background jobs last ran",
    auth: "admin",
    limits: ["user"],
    responses: ok("AdminOverviewResponse"),
  },
  {
    method: "get",
    path: "/api/admin/checks",
    tag: "Admin",
    summary:
      "What the setup checks read: APP_URL, what the proxy does to X-Forwarded-For, backups and mail",
    auth: "admin",
    limits: ["user"],
    responses: ok("AdminChecksResponse"),
  },
  {
    method: "post",
    path: "/api/admin/checks/mail",
    tag: "Admin",
    summary: "Send a test message to the admin's own email address",
    auth: "admin",
    limits: ["user"],
    responses: {
      ...ok("AdminTestMailResponse"),
      "409": {
        description: "Mail is not set up, or the account has no address",
        schema: "Error",
      },
    },
  },
  {
    method: "get",
    path: "/api/admin/audit",
    tag: "Admin",
    summary: "The audit log, newest first",
    auth: "admin",
    limits: ["user"],
    query: {
      limit: "Entries per page (up to 500)",
      before: "An entry id; older entries only",
      userId: "Entries where this account acted or was acted on",
      action: "One kind of entry",
    },
    responses: ok("AuditLogResponse"),
  },
  {
    method: "post",
    path: "/api/admin/users",
    tag: "Admin",
    summary: "Create an account with a temporary password",
    auth: "admin",
    limits: ["user"],
    body: adminCreateUserSchema,
    responses: {
      "201": {
        description: "Created",
        schema: "AdminTemporaryPasswordResponse",
      },
    },
  },
  {
    method: "put",
    path: "/api/admin/users/:id",
    tag: "Admin",
    summary: "Grant or take admin, or set an email address",
    auth: "admin",
    limits: ["user"],
    body: adminUpdateUserSchema,
    responses: ok("AdminUserResponse"),
  },
  {
    method: "post",
    path: "/api/admin/users/:id/password",
    tag: "Admin",
    summary: "Issue a temporary password; the user's sessions end",
    auth: "admin",
    limits: ["user"],
    responses: ok("AdminTemporaryPasswordResponse"),
  },
  {
    method: "delete",
    path: "/api/admin/users/:id",
    tag: "Admin",
    summary: "Delete an account and its notes",
    auth: "admin",
    limits: ["user"],
    responses: noContent,
  },
];
