import {
  passkeyAddSchema,
  passkeyLoginSchema,
  twoFactorEnableSchema,
  twoFactorPasswordSchema,
} from "../validation/schemas.js";
import { noContent, notFound, type Operation, ok } from "./operation.js";

/** Second factors and passkeys, set up by an account and used to sign in. */
export const AUTH_FACTOR_OPERATIONS: Operation[] = [
  {
    method: "get",
    path: "/api/auth/two-factor",
    tag: "Auth",
    summary: "Whether two-factor sign-in is on, and recovery codes left",
    auth: "session",
    limits: [],
    responses: ok("TwoFactorStatusResponse"),
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/two-factor/setup",
    tag: "Auth",
    summary: "Start turning two-factor on: a new authenticator secret",
    auth: "session",
    feature: "twoFactor",
    limits: ["sign-in"],
    body: twoFactorPasswordSchema,
    responses: ok("TwoFactorSetupResponse"),
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/two-factor/enable",
    tag: "Auth",
    summary: "Confirm with a code; answers the recovery codes, once",
    auth: "session",
    feature: "twoFactor",
    limits: ["sign-in"],
    body: twoFactorEnableSchema,
    responses: ok("TwoFactorRecoveryCodesResponse"),
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/two-factor/disable",
    tag: "Auth",
    summary: "Turn two-factor off",
    auth: "session",
    limits: ["sign-in"],
    body: twoFactorPasswordSchema,
    responses: noContent,
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/two-factor/recovery-codes",
    tag: "Auth",
    summary: "Replace the recovery codes",
    auth: "session",
    limits: ["sign-in"],
    body: twoFactorPasswordSchema,
    responses: ok("TwoFactorRecoveryCodesResponse"),
    provider: "local",
  },
  {
    method: "get",
    path: "/api/auth/passkeys",
    tag: "Auth",
    summary: "The account's passkeys, without their keys",
    auth: "session",
    limits: [],
    responses: ok("PasskeysResponse"),
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/passkeys/options",
    tag: "Auth",
    summary:
      "Start adding a passkey, with the password: options for navigator.credentials.create()",
    auth: "session",
    feature: "passkeys",
    limits: ["sign-in"],
    body: twoFactorPasswordSchema,
    responses: ok("PasskeyOptionsResponse"),
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/passkeys",
    tag: "Auth",
    summary:
      "Add the passkey the browser made; answers the recovery codes when it is the first second factor",
    auth: "session",
    feature: "passkeys",
    limits: ["sign-in"],
    body: passkeyAddSchema,
    responses: {
      "201": { description: "Added", schema: "PasskeyAddedResponse" },
    },
    provider: "local",
  },
  {
    method: "delete",
    path: "/api/auth/passkeys/:id",
    tag: "Auth",
    summary: "Remove a passkey, with the password",
    auth: "session",
    limits: ["sign-in"],
    body: twoFactorPasswordSchema,
    responses: { ...noContent, ...notFound },
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/passkey/options",
    tag: "Auth",
    summary:
      "A challenge to sign in with a passkey alone, for navigator.credentials.get()",
    auth: "none",
    feature: "passkeys",
    limits: ["passkey-sign-in"],
    responses: ok("PasskeySignInOptionsResponse"),
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/passkey/login",
    tag: "Auth",
    summary: "Sign in with a passkey's answer to that challenge",
    auth: "none",
    feature: "passkeys",
    limits: ["passkey-sign-in"],
    body: passkeyLoginSchema,
    responses: ok("AuthSuccess"),
    provider: "local",
  },
];
