import {
  accountPrefsUpdateSchema,
  authLocaleSchema,
  authMeUpdateSchema,
  loginSchema,
  passwordChangeSchema,
  passwordResetConfirmSchema,
  passwordResetRequestSchema,
  registerSchema,
  signInLinkConfirmSchema,
  signInLinkRequestSchema,
} from "../validation/schemas.js";
import { noContent, type Operation, ok } from "./operation.js";

/**
 * The signed-in account and the ways into and out of it: register, sign in,
 * passwords.
 */
export const AUTH_OPERATIONS: Operation[] = [
  {
    method: "get",
    path: "/api/auth/me",
    tag: "Auth",
    summary: "The signed-in user",
    auth: "any",
    limits: [],
    scope: "account:read",
    responses: ok("AuthMeResponse"),
  },
  {
    method: "put",
    path: "/api/auth/me",
    tag: "Auth",
    summary: "Set or clear the signed-in user's email address",
    auth: "session",
    limits: [],
    body: authMeUpdateSchema,
    responses: ok("AuthMeResponse"),
  },
  {
    method: "get",
    path: "/api/auth/me/activity",
    tag: "Auth",
    summary: "The signed-in user's own lines of the audit log, newest first",
    auth: "session",
    limits: [],
    query: {
      limit: "Entries per page (up to 500)",
      before: "An entry id; older entries only",
    },
    responses: ok("AuditLogResponse"),
  },
  {
    method: "get",
    path: "/api/auth/me/prefs",
    tag: "Auth",
    summary: "The signed-in user's preferences, as their clients sent them",
    auth: "any",
    limits: [],
    scope: "account:read",
    responses: ok("AccountPrefsResponse"),
  },
  {
    method: "patch",
    path: "/api/auth/me/prefs",
    tag: "Auth",
    summary: "Set some of the signed-in user's preferences; null removes one",
    auth: "any",
    limits: [],
    scope: "account:write",
    body: accountPrefsUpdateSchema,
    responses: {
      ...ok("AccountPrefsResponse"),
      "413": { description: "Over the size limit", schema: "Error" },
    },
  },
  {
    method: "put",
    path: "/api/auth/me/locale",
    tag: "Auth",
    summary: "Record the language the signed-in user's client is set to",
    auth: "any",
    limits: [],
    scope: "account:write",
    body: authLocaleSchema,
    responses: noContent,
  },
  {
    method: "post",
    path: "/api/auth/register",
    tag: "Auth",
    summary: "Create an account (local sign-in, when registration is open)",
    auth: "none",
    limits: ["sign-in"],
    body: registerSchema,
    responses: { "201": { description: "Signed in", schema: "AuthSuccess" } },
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/login",
    tag: "Auth",
    summary: "Sign in with a username and password",
    auth: "none",
    limits: ["sign-in"],
    body: loginSchema,
    responses: ok("AuthSuccess"),
    provider: "local",
  },
  {
    method: "get",
    path: "/api/auth/login",
    tag: "Auth",
    summary: "Start single sign-on (redirects to the identity provider)",
    auth: "none",
    limits: ["oidc"],
    query: {
      reauth:
        "Present: the identity provider asks the user to sign in again (prompt=login), for an action that needs a recent sign-in",
    },
    responses: { "302": { description: "To the identity provider" } },
    provider: "oidc",
  },
  {
    method: "get",
    path: "/api/auth/callback",
    tag: "Auth",
    summary: "Where the identity provider returns to",
    auth: "none",
    limits: ["oidc"],
    responses: { "302": { description: "To the client, with a token" } },
    provider: "oidc",
  },
  {
    method: "post",
    path: "/api/auth/logout",
    tag: "Auth",
    summary: "End this session",
    auth: "session",
    limits: [],
    responses: noContent,
  },
  {
    method: "post",
    path: "/api/auth/password",
    tag: "Auth",
    summary: "Change the signed-in user's password; other sessions end",
    auth: "session",
    limits: ["sign-in"],
    body: passwordChangeSchema,
    responses: noContent,
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/password-reset",
    tag: "Auth",
    summary: "Mail a reset link to a local account's address; always 204",
    auth: "none",
    limits: ["sign-in"],
    body: passwordResetRequestSchema,
    responses: noContent,
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/password-reset/confirm",
    tag: "Auth",
    summary: "Set a new password with a link's token; ends every session",
    auth: "none",
    limits: ["sign-in"],
    body: passwordResetConfirmSchema,
    responses: {
      ...noContent,
      "410": { description: "Expired or used", schema: "Error" },
    },
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/sign-in-link",
    tag: "Auth",
    summary: "Mail a sign-in link to a local account's address; always 204",
    auth: "none",
    limits: ["sign-in"],
    feature: "magicLinks",
    body: signInLinkRequestSchema,
    responses: noContent,
    provider: "local",
  },
  {
    method: "post",
    path: "/api/auth/sign-in-link/confirm",
    tag: "Auth",
    summary:
      "Sign in with a link's token, and the second factor if the account has one",
    auth: "none",
    limits: ["sign-in"],
    feature: "magicLinks",
    body: signInLinkConfirmSchema,
    responses: {
      ...ok("AuthSuccess"),
      "401": { description: "Wrong second factor", schema: "Error" },
      "403": {
        description: "A second factor is required",
        schema: "TwoFactorRequired",
      },
      "410": { description: "Expired or used", schema: "Error" },
      "429": {
        description:
          "Too many failed sign-ins for the account; Retry-After says how long",
        schema: "Error",
      },
    },
    provider: "local",
  },
];
