import {
  noteCreateSchema,
  notesImportSchema,
  noteUpdateSchema,
  noteVersionCreateSchema,
} from "../validation/schemas.js";
import { noContent, notFound, type Operation, ok } from "./operation.js";

/**
 * Notes, their versions, attachments and link previews, and the ways to read
 * them in bulk.
 */
export const NOTE_OPERATIONS: Operation[] = [
  {
    method: "get",
    path: "/api/notes",
    tag: "Notes",
    summary: "One page of the user's notes, newest first, without images",
    auth: "any",
    limits: ["user"],
    scope: "notes:read",
    query: { limit: "Page size", cursor: "From the previous page" },
    responses: ok("NotesResponse"),
  },
  {
    method: "post",
    path: "/api/notes",
    tag: "Notes",
    summary: "Create a note",
    auth: "any",
    limits: ["user"],
    scope: "notes:write",
    body: noteCreateSchema,
    responses: { "201": { description: "Created", schema: "NoteResponse" } },
  },
  {
    method: "post",
    path: "/api/notes/import",
    tag: "Notes",
    summary:
      "Import up to 100 notes, keeping their ids; the same one twice updates it",
    auth: "any",
    limits: ["user"],
    scope: "notes:write",
    body: notesImportSchema,
    responses: ok("NotesImportResponse"),
  },
  {
    method: "delete",
    path: "/api/notes",
    tag: "Notes",
    summary: "Delete every note the user owns (shared ones stay)",
    auth: "any",
    limits: ["user"],
    scope: "notes:write",
    responses: noContent,
  },
  {
    method: "get",
    path: "/api/notes/:id",
    tag: "Notes",
    summary: "One note, with its images",
    auth: "any",
    limits: ["user"],
    scope: "notes:read",
    responses: { ...ok("NoteResponse"), ...notFound },
  },
  {
    method: "put",
    path: "/api/notes/:id",
    tag: "Notes",
    summary: "Change a note; send If-Match for a compare-and-set",
    auth: "any",
    limits: ["user"],
    scope: "notes:write",
    body: noteUpdateSchema,
    responses: {
      ...ok("NoteResponse"),
      "403": { description: "Your role does not allow it", schema: "Error" },
      ...notFound,
      "412": { description: "Changed since; carries the current note" },
    },
  },
  {
    method: "delete",
    path: "/api/notes/:id",
    tag: "Notes",
    summary: "Delete a note (a recipient leaves it instead)",
    auth: "any",
    limits: ["user"],
    scope: "notes:write",
    responses: { ...noContent, ...notFound },
  },
  {
    method: "get",
    path: "/api/notes/:id/versions",
    tag: "Notes",
    summary: "The note's version history, newest first",
    auth: "any",
    limits: ["user"],
    scope: "notes:read",
    responses: ok("NoteVersionsResponse"),
  },
  {
    method: "post",
    path: "/api/notes/:id/versions",
    tag: "Notes",
    summary: "Add a version (owner and editors)",
    auth: "any",
    limits: ["user"],
    scope: "notes:write",
    body: noteVersionCreateSchema,
    responses: { "201": { description: "Added" } },
  },
  {
    method: "get",
    path: "/api/calendar/:file",
    tag: "Notes",
    summary:
      "The reminders as an iCalendar feed, at <calendar token>.ics; no header, the token is the address",
    auth: "none",
    feature: "calendar",
    limits: ["calendar"],
    responses: { "200": { description: "text/calendar" }, ...notFound },
  },
  {
    method: "get",
    path: "/api/sync",
    tag: "Notes",
    summary:
      "The notes changed since a checkpoint, and on the last page every visible id and the next checkpoint",
    auth: "any",
    limits: ["user"],
    scope: "notes:read",
    query: {
      since: "The checkpoint of the previous sync; omit for everything",
      limit: "Page size",
      cursor: "From the previous page",
    },
    responses: ok("SyncResponse"),
  },
  {
    method: "get",
    path: "/api/search",
    tag: "Notes",
    summary: "Notes whose title or content contains q, newest first",
    auth: "any",
    limits: ["user"],
    scope: "notes:read",
    query: { q: "Search words", limit: "Page size", cursor: "Next page" },
    responses: ok("NotesResponse"),
  },
  {
    method: "post",
    path: "/api/attachments",
    tag: "Notes",
    summary:
      "Upload an image (the raw file, its type in Content-Type); answers the attachment: reference",
    auth: "any",
    limits: ["attachments"],
    scope: "notes:write",
    responses: {
      "201": { description: "Stored", schema: "AttachmentUploadResponse" },
      "413": { description: "Over the image limit", schema: "Error" },
      "415": { description: "Not an accepted image type", schema: "Error" },
    },
  },
  {
    method: "get",
    path: "/api/attachments/:id",
    tag: "Notes",
    summary: "The bytes of an image a note refers to as attachment:<id>",
    auth: "any",
    limits: ["attachments"],
    scope: "notes:read",
    responses: {
      "200": { description: "The image, with its media type" },
      ...notFound,
    },
  },
  {
    method: "get",
    path: "/api/link-preview",
    tag: "Notes",
    summary: "What the server could read from a linked page",
    auth: "any",
    feature: "linkPreviews",
    limits: ["user", "link-preview"],
    scope: "notes:write",
    query: { url: "An http(s) URL" },
    responses: ok("LinkPreviewResponse"),
  },
];
