import {
  noteCommentSchema,
  publicLinkCreateSchema,
  publicLinkUnlockSchema,
  publicNoteUpdateSchema,
  shareCreateSchema,
  shareUpdateSchema,
  teamShareCreateSchema,
} from "../validation/schemas.js";
import { noContent, notFound, type Operation, ok } from "./operation.js";

/**
 * Sharing a note: with accounts and teams, by invitation, and through public
 * links.
 */
export const SHARING_OPERATIONS: Operation[] = [
  {
    method: "post",
    path: "/api/notes/:id/shares",
    tag: "Sharing",
    summary: "Invite an account to the note (owner)",
    auth: "any",
    feature: "sharing",
    limits: ["user"],
    scope: "sharing",
    body: shareCreateSchema,
    responses: { "201": { description: "Invited", schema: "NoteResponse" } },
  },
  {
    method: "put",
    path: "/api/notes/:id/shares/:userId",
    tag: "Sharing",
    summary: "Change someone's role (owner)",
    auth: "any",
    feature: "sharing",
    limits: ["user"],
    scope: "sharing",
    body: shareUpdateSchema,
    responses: ok("NoteResponse"),
  },
  {
    method: "delete",
    path: "/api/notes/:id/shares/:userId",
    tag: "Sharing",
    summary: "Remove someone, or leave the note yourself",
    auth: "any",
    limits: ["user"],
    scope: "sharing",
    responses: noContent,
  },
  {
    method: "get",
    path: "/api/teams",
    tag: "Sharing",
    summary: "The teams the user is in, to share notes with",
    auth: "any",
    feature: "teams",
    limits: ["user"],
    scope: "sharing",
    responses: ok("TeamsResponse"),
  },
  {
    method: "get",
    path: "/api/notes/:id/team-shares",
    tag: "Sharing",
    summary: "The teams the note is shared with (owner)",
    auth: "any",
    limits: ["user"],
    scope: "sharing",
    responses: { ...ok("TeamSharesResponse"), ...notFound },
  },
  {
    method: "post",
    path: "/api/notes/:id/team-shares",
    tag: "Sharing",
    summary:
      "Share the note with a team the owner is in, inviting its members (owner)",
    auth: "any",
    feature: "teams",
    limits: ["user"],
    scope: "sharing",
    body: teamShareCreateSchema,
    responses: {
      "201": { description: "Shared", schema: "TeamSharesResponse" },
      ...notFound,
    },
  },
  {
    method: "put",
    path: "/api/notes/:id/team-shares/:teamId",
    tag: "Sharing",
    summary: "Change the role a team has, and its members' with it (owner)",
    auth: "any",
    feature: "teams",
    limits: ["user"],
    scope: "sharing",
    body: shareUpdateSchema,
    responses: { ...ok("TeamSharesResponse"), ...notFound },
  },
  {
    method: "delete",
    path: "/api/notes/:id/team-shares/:teamId",
    tag: "Sharing",
    summary: "Stop sharing the note with a team (owner)",
    auth: "any",
    limits: ["user"],
    scope: "sharing",
    responses: { ...noContent, ...notFound },
  },
  {
    method: "get",
    path: "/api/notes/:id/links",
    tag: "Sharing",
    summary: "The note's public links, with their view counts (owner)",
    auth: "any",
    feature: "publicLinks",
    limits: ["user"],
    scope: "sharing",
    responses: { ...ok("PublicLinksResponse"), ...notFound },
  },
  {
    method: "post",
    path: "/api/notes/:id/links",
    tag: "Sharing",
    summary:
      "Publish the note by a revocable public link, live or as a snapshot (owner)",
    auth: "any",
    feature: "publicLinks",
    limits: ["user"],
    scope: "sharing",
    body: publicLinkCreateSchema,
    responses: {
      "201": { description: "Published", schema: "PublicLinkResponse" },
      ...notFound,
    },
  },
  {
    method: "delete",
    path: "/api/notes/:id/links/:token",
    tag: "Sharing",
    summary: "Revoke a public link (owner)",
    auth: "any",
    feature: "publicLinks",
    limits: ["user"],
    scope: "sharing",
    responses: { ...noContent, ...notFound },
  },
  {
    method: "get",
    path: "/api/public/:token",
    tag: "Sharing",
    summary:
      "A note by public link, counting a view; 401 with passwordRequired when it has a password",
    auth: "none",
    feature: "publicLinks",
    limits: ["public-links"],
    responses: {
      ...ok("PublicNoteResponse"),
      "401": {
        description: "The link has a password",
        schema: "PublicNoteLockedResponse",
      },
      ...notFound,
    },
  },
  {
    method: "post",
    path: "/api/public/:token/unlock",
    tag: "Sharing",
    summary: "A note by public link with a password, counting a view",
    auth: "none",
    feature: "publicLinks",
    limits: ["public-links", "public-link-unlock"],
    body: publicLinkUnlockSchema,
    responses: {
      ...ok("PublicNoteResponse"),
      "403": { description: "Wrong password", schema: "Error" },
      ...notFound,
    },
  },
  {
    method: "put",
    path: "/api/public/:token",
    tag: "Sharing",
    summary:
      "Change the title or text through a public link that can edit; send If-Match, and X-Link-Access for a link with a password",
    auth: "none",
    feature: "publicLinks",
    limits: ["public-links", "public-link-edit"],
    body: publicNoteUpdateSchema,
    responses: {
      ...ok("PublicNoteResponse"),
      "412": { description: "Changed meanwhile", schema: "PublicNoteResponse" },
      ...notFound,
    },
  },
  {
    method: "get",
    path: "/api/public/:token/attachments/:id",
    tag: "Sharing",
    summary:
      "A picture the linked note shows; send X-Link-Access for a link with a password",
    auth: "none",
    feature: "publicLinks",
    limits: ["public-links"],
    responses: { "200": { description: "The image" }, ...notFound },
  },
  {
    method: "get",
    path: "/api/invitations",
    tag: "Sharing",
    summary: "Notes offered to the user",
    auth: "any",
    feature: "sharing",
    limits: ["user"],
    scope: "sharing",
    responses: ok("InvitationsResponse"),
  },
  {
    method: "post",
    path: "/api/invitations/:noteId/accept",
    tag: "Sharing",
    summary: "Accept an invitation",
    auth: "any",
    feature: "sharing",
    limits: ["user"],
    scope: "sharing",
    responses: ok("NoteResponse"),
  },
  {
    method: "post",
    path: "/api/invitations/:noteId/decline",
    tag: "Sharing",
    summary: "Decline an invitation",
    auth: "any",
    feature: "sharing",
    limits: ["user"],
    scope: "sharing",
    responses: noContent,
  },
  {
    method: "get",
    path: "/api/users",
    tag: "Sharing",
    summary: "Find accounts to share with",
    auth: "any",
    feature: "sharing",
    limits: ["user"],
    scope: "sharing",
    query: { q: "Name, username or email address" },
    responses: ok("UserLookupResponse"),
  },
  {
    method: "get",
    path: "/api/notes/:id/comments",
    tag: "Sharing",
    summary: "The comments beside a note, oldest first",
    auth: "any",
    limits: ["user"],
    scope: "notes:read",
    responses: { ...ok("NoteCommentsResponse"), ...notFound },
  },
  {
    method: "post",
    path: "/api/notes/:id/comments",
    tag: "Sharing",
    summary: "Comment on a note (anyone who can see it)",
    auth: "any",
    feature: "sharing",
    limits: ["user"],
    scope: "notes:write",
    body: noteCommentSchema,
    responses: {
      "201": { description: "Written", schema: "NoteCommentResponse" },
      "409": { description: "The note holds no more", schema: "Error" },
    },
  },
  {
    method: "put",
    path: "/api/notes/:id/comments/:commentId",
    tag: "Sharing",
    summary: "Change a comment (its author)",
    auth: "any",
    feature: "sharing",
    limits: ["user"],
    scope: "notes:write",
    body: noteCommentSchema,
    responses: ok("NoteCommentResponse"),
  },
  {
    method: "delete",
    path: "/api/notes/:id/comments/:commentId",
    tag: "Sharing",
    summary: "Delete a comment (its author, or the note's owner)",
    auth: "any",
    limits: ["user"],
    scope: "notes:write",
    responses: noContent,
  },
];
