import { NoteColor } from "@manifesto/shared";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  AUTO_NOTE_OVERRIDE_FIELDS,
  autoNoteOverrides,
  generatedNoteId,
  isGeneratedNoteId,
  overrideFrom,
} from "./autoNoteOverrides.js";
import { autoNotes, generatedNotes } from "./autoNotes.js";
import {
  deleteNote,
  notes,
  updateNote,
  updateStoredNote,
} from "./notesStore.js";

/**
 * An auto-note is regenerated by its plugin on every run, so what the user
 * does to it (pin, colour, tags, archive, trash, position, reminder) lives in
 * a sidecar keyed by its generated id and is laid over whatever the plugin
 * returns. The plugin is not run here: `autoNotes` is set directly, as the
 * sandbox would set it.
 */

const STORAGE_KEY = "manifesto:auto-note-overrides";
const ID = generatedNoteId("weather", "today");

function renderPlugin(title = "Sunny", extra: Record<string, unknown> = {}) {
  autoNotes.value = [
    {
      pluginId: "weather",
      pluginName: "Weather",
      result: { title, content: "22 degrees", key: "today", ...extra },
    },
  ];
}

function generated() {
  const found = generatedNotes.value.find((n) => n.id === ID);
  if (!found) throw new Error("the auto-note is missing");
  return found;
}

beforeEach(() => {
  localStorage.clear();
  notes.value = [];
  autoNoteOverrides.value = {};
  autoNotes.value = [];
});

afterEach(() => {
  autoNotes.value = [];
  autoNoteOverrides.value = {};
  localStorage.clear();
});

describe("generated ids", () => {
  it("name the plugin and the note, and are told apart from stored ids", () => {
    expect(ID).toBe("generated:weather:today");
    expect(isGeneratedNoteId(ID)).toBe(true);
    expect(isGeneratedNoteId("01J8Z3Q4R5S6T7V8W9X0Y1Z2AB")).toBe(false);
  });
});

describe("overrideFrom", () => {
  it("keeps what the user may set and drops the plugin's title and content", () => {
    expect(
      overrideFrom({
        title: "mine now",
        content: "rewritten",
        font: "serif" as never,
        pinned: true,
        color: NoteColor.Green,
        tags: ["t"],
        position: 3,
        trashed: false,
        archived: undefined,
      }),
    ).toEqual({
      pinned: true,
      color: NoteColor.Green,
      tags: ["t"],
      position: 3,
      trashed: false,
    });
  });
});

describe("an auto-note's overrides", () => {
  it("lay the user's changes over the plugin's note, and survive the next run", async () => {
    renderPlugin("Sunny", { color: NoteColor.Yellow, tags: ["plugin"] });
    await updateNote(ID, {
      pinned: true,
      color: NoteColor.Blue,
      tags: ["mine"],
      title: "ignored",
    });
    expect(generated()).toMatchObject({
      title: "Sunny",
      pinned: true,
      color: NoteColor.Blue,
      tags: ["mine"],
      readonly: true,
    });
    renderPlugin("Rainy", { color: NoteColor.Yellow });
    expect(generated()).toMatchObject({
      title: "Rainy",
      pinned: true,
      color: NoteColor.Blue,
    });
    // Never written to the stored notes.
    expect(notes.value).toEqual([]);
  });

  it("merge one change into the last rather than replacing it", async () => {
    renderPlugin();
    await updateNote(ID, { pinned: true });
    await updateNote(ID, { archived: true });
    expect(autoNoteOverrides.value[ID]).toEqual({
      pinned: true,
      archived: true,
    });
  });

  it("put an auto-note in the trash and bring it back", async () => {
    renderPlugin();
    await updateNote(ID, { trashed: true, trashedAt: "2026-01-01T00:00:00Z" });
    expect(generated()).toMatchObject({
      trashed: true,
      trashedAt: "2026-01-01T00:00:00Z",
    });
    await updateNote(ID, { trashed: false, trashedAt: null });
    expect(generated()).toMatchObject({ trashed: false, trashedAt: null });
  });

  it("are forgotten when the note is deleted, and the plugin's note comes back as it was", async () => {
    renderPlugin();
    await updateNote(ID, { pinned: true });
    expect(await deleteNote(ID)).toBe(true);
    expect(autoNoteOverrides.value).toEqual({});
    expect(generated().pinned).toBe(false);
  });

  it("are kept in localStorage", async () => {
    renderPlugin();
    await updateNote(ID, { tags: ["kept"] });
    await vi.waitFor(() =>
      expect(JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "{}")).toEqual({
        [ID]: { tags: ["kept"] },
      }),
    );
  });

  it("cover every personal field a note has", () => {
    expect([...AUTO_NOTE_OVERRIDE_FIELDS].sort()).toEqual(
      [
        "archived",
        "color",
        "pinned",
        "position",
        "reminder",
        "tags",
        "trashed",
        "trashedAt",
      ].sort(),
    );
  });

  it("report a change that was made as made", async () => {
    renderPlugin();
    expect(await updateNote(ID, { pinned: true })).toBe(true);
  });

  it("hand back the note as the change left it", async () => {
    renderPlugin();
    const stored = await updateStoredNote(ID, { color: NoteColor.Blue });
    expect(stored).toMatchObject({
      id: ID,
      title: "Sunny",
      color: NoteColor.Blue,
    });
  });

  it("report a note the plugin no longer makes as not changed", async () => {
    expect(await updateNote(ID, { pinned: true })).toBe(false);
  });
});

let loads = 0;

/** The module as a fresh page load would evaluate it, reading localStorage. */
async function loadAfresh(): Promise<typeof import("./autoNoteOverrides.js")> {
  loads++;
  const path = `./autoNoteOverrides.js?load=${loads}`;
  return await import(/* @vite-ignore */ path);
}

describe("overrides read back from localStorage", () => {
  it("keep the valid entries of a hand-edited blob and drop the rest", async () => {
    localStorage.setItem(
      STORAGE_KEY,
      JSON.stringify({
        "generated:a:1": { pinned: true, tags: ["x"] },
        "generated:a:2": { pinned: "yes" },
        "generated:a:3": { tags: ["ok", 5] },
        "generated:a:4": { reminder: { time: 42 } },
        "generated:a:5": { position: "first" },
        "generated:a:6": null,
        "generated:a:7": { reminder: null, trashedAt: null },
      }),
    );
    const fresh = await loadAfresh();
    expect(fresh.autoNoteOverrides.value).toEqual({
      "generated:a:1": { pinned: true, tags: ["x"] },
      "generated:a:7": { reminder: null, trashedAt: null },
    });
  });

  it("start empty from a blob that is not an object of overrides", async () => {
    for (const raw of ["not json", "[]", "null", '"text"']) {
      localStorage.setItem(STORAGE_KEY, raw);
      const fresh = await loadAfresh();
      expect(fresh.autoNoteOverrides.value, raw).toEqual({});
    }
  });
});
