import type { NoteUpdate } from "@manifesto/shared";
import { effect, signal } from "@preact/signals";

/**
 * Per-auto-note overrides. Auto-notes are regenerated by their plugin on
 * every run, so any user-set metadata (pin, color, tags, archive, trash,
 * reminder, position) lives in this sidecar keyed by the note's synthetic
 * id (`generated:<pluginId>:<noteKey>`). Overrides merge on top of whatever
 * the plugin emits.
 */
export const AUTO_NOTE_OVERRIDE_FIELDS = [
  "pinned",
  "color",
  "tags",
  "archived",
  "trashed",
  "trashedAt",
  "position",
  "reminder",
] as const satisfies readonly (keyof NoteUpdate)[];

export type AutoNoteOverride = Pick<
  NoteUpdate,
  (typeof AUTO_NOTE_OVERRIDE_FIELDS)[number]
>;

const GENERATED_ID_PREFIX = "generated:";

/** The synthetic id an auto-note is known by. */
export function generatedNoteId(pluginId: string, noteKey: string): string {
  return `${GENERATED_ID_PREFIX}${pluginId}:${noteKey}`;
}

/** Whether a note id names an auto-note rather than a stored note. */
export function isGeneratedNoteId(id: string): boolean {
  return id.startsWith(GENERATED_ID_PREFIX);
}

/** The part of `changes` an auto-note keeps; its title and content are the
 * plugin's. */
export function overrideFrom(changes: NoteUpdate): AutoNoteOverride {
  const override: Record<string, unknown> = {};
  for (const field of AUTO_NOTE_OVERRIDE_FIELDS) {
    if (changes[field] !== undefined) override[field] = changes[field];
  }
  return override as AutoNoteOverride;
}

const STORAGE_KEY = "manifesto:auto-note-overrides";

function isValidOverride(v: unknown): v is AutoNoteOverride {
  if (!v || typeof v !== "object") return false;
  const o = v as Record<string, unknown>;
  if (o.pinned !== undefined && typeof o.pinned !== "boolean") return false;
  if (o.color !== undefined && typeof o.color !== "string") return false;
  if (o.archived !== undefined && typeof o.archived !== "boolean") return false;
  if (o.trashed !== undefined && typeof o.trashed !== "boolean") return false;
  if (
    o.trashedAt !== undefined &&
    o.trashedAt !== null &&
    typeof o.trashedAt !== "string"
  )
    return false;
  if (o.position !== undefined && typeof o.position !== "number") return false;
  if (o.tags !== undefined) {
    if (!Array.isArray(o.tags)) return false;
    if (!o.tags.every((t) => typeof t === "string")) return false;
  }
  if (o.reminder !== undefined && o.reminder !== null) {
    if (typeof o.reminder !== "object") return false;
    const r = o.reminder as Record<string, unknown>;
    if (typeof r.time !== "string") return false;
  }
  return true;
}

function load(): Record<string, AutoNoteOverride> {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return {};
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      return {};
    }
    const out: Record<string, AutoNoteOverride> = {};
    for (const [id, val] of Object.entries(parsed as Record<string, unknown>)) {
      if (isValidOverride(val)) out[id] = val;
    }
    return out;
  } catch {
    return {};
  }
}

export const autoNoteOverrides = signal<Record<string, AutoNoteOverride>>(
  load(),
);

effect(() => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(autoNoteOverrides.value));
  } catch {
    // Ignore quota/access failures.
  }
});

function merge(
  current: AutoNoteOverride | undefined,
  patch: AutoNoteOverride,
): AutoNoteOverride {
  return { ...(current ?? {}), ...patch };
}

export function updateAutoNoteOverride(id: string, patch: AutoNoteOverride) {
  const current = autoNoteOverrides.value;
  const next = { ...current, [id]: merge(current[id], patch) };
  autoNoteOverrides.value = next;
}

export function clearAutoNoteOverride(id: string) {
  const current = autoNoteOverrides.value;
  if (!(id in current)) return;
  const next = { ...current };
  delete next[id];
  autoNoteOverrides.value = next;
}
