// Barrel re-export — all public state, actions, and types

export {
  addTagToNotes,
  allTags,
  archiveNote,
  bulkAddTag,
  bulkArchive,
  bulkDelete,
  bulkPin,
  bulkSetColor,
  bulkTrash,
  canReorder,
  createNote,
  deleteAllNotes,
  deleteCheckedItems,
  deleteTag,
  editingNote,
  enterSelectMode,
  exitSelectMode,
  expireTrash,
  exportNotes,
  filteredNotes,
  hasCheckedItems,
  importNotes,
  loadNotes,
  notes,
  permanentlyDeleteNote,
  pickDefaultColor,
  pickDefaultFont,
  pinnedNotes,
  reorderNotes,
  restoreNote,
  sortedNotes,
  toggleCheckbox,
  togglePin,
  toggleSelectNote,
  trashNote,
  unarchiveNote,
  unpinnedNotes,
  updateNote,
} from "./actions.js";
export {
  type DecimalSeparator,
  type DefaultNoteColor,
  type DefaultNoteFont,
  decimalSeparator,
  defaultNoteColor,
  defaultNoteFont,
  inlineCalculations,
  locale,
  type NoteSize,
  noteSize,
  resolvedDecimalSeparator,
  type SortMode,
  sortMode,
  type ThemeMode,
  theme,
  type ViewMode,
  viewMode,
} from "./prefs.js";
export {
  buildPath as buildRoutePath,
  initRouter,
  parsePath as parseRoutePath,
  type Route,
  stopRouter,
} from "./router.js";
export {
  type AppView,
  activeTag,
  activeView,
  dismissError,
  dismissToast,
  editingNoteId,
  errors,
  mobileSidebarOpen,
  searchQuery,
  selectedNotes,
  selectMode,
  showError,
  showSettings,
  showSuccess,
  tagsShowArchived,
  tagsShowTrashed,
  toasts,
} from "./ui.js";
