// Barrel re-export of all public state, actions, and types

export {
  addTag,
  addTagToNotes,
  archiveNote,
  bulkArchive,
  bulkDelete,
  bulkPin,
  bulkRestore,
  bulkSetColor,
  bulkSetTag,
  bulkTrash,
  deleteCheckedItems,
  deleteTag,
  type LeaveStyle,
  leavingNotes,
  permanentlyDeleteNote,
  recentlyPinned,
  renameTag,
  reorderNotes,
  restoreNote,
  sortItemsByDate,
  toggleCheckbox,
  togglePin,
  trashNote,
  unarchiveNote,
} from "./actions.js";
export { downloadExport, exportNotes } from "./exportNotes.js";
export {
  addLinkPreviews,
  applyLinkPreviews,
  reportPreviewOverflow,
  resolveLinkPreview,
} from "./linkPreviews.js";
export {
  allNotes,
  createNote,
  deleteAllNotes,
  ensureImages,
  expireTrash,
  importNotes,
  loadNotes,
  notes,
  notesLoaded,
  receiveNote,
  updateNote,
  updateStoredNote,
} from "./notesStore.js";
export {
  animations,
  BOARD_COLORS,
  BOARD_TEXTURES,
  type BoardColor,
  type BoardColorChoice,
  type BoardTexture,
  type BoardTextureChoice,
  boardColor,
  boardCustomColor,
  boardImageStamp,
  boardTexture,
  boardUsePicture,
  confirmBeforeDelete,
  DARK_HUES,
  type DarkHue,
  type DecimalSeparator,
  type DefaultNoteColor,
  type DefaultNoteFont,
  darkHue,
  decimalSeparator,
  defaultEditMode,
  defaultNoteColor,
  defaultNoteFont,
  type EditMode,
  formattingToolbar,
  hiddenTags,
  inlineCalculations,
  locale,
  type NoteCorners,
  type NoteScale,
  type NoteSize,
  noteCorners,
  noteQuips,
  noteScale,
  noteSize,
  pickDefaultColor,
  pickDefaultFont,
  rerollBoardColor,
  rerollBoardTexture,
  resolvedBoardColor,
  resolvedBoardTexture,
  resolvedDecimalSeparator,
  type SortMode,
  sortMode,
  stickyTopBar,
  type TagColor,
  type ThemeMode,
  tagColors,
  theme,
  type ViewMode,
  viewMode,
} from "./prefs.js";
export {
  buildPath as buildRoutePath,
  initRouter,
  parsePath as parseRoutePath,
  type Route,
  stopRouter,
} from "./router.js";
export {
  enterSelectMode,
  exitSelectMode,
  selectAllVisible,
  toggleSelectNote,
} from "./selection.js";
export {
  fromTemplate,
  isTemplateTag,
  TEMPLATE_TAG,
  templateName,
  templates,
} from "./templates.js";
export {
  type AppView,
  activeTag,
  activeView,
  clearSearchFilters,
  dismissToast,
  editingNoteId,
  exitSearch,
  newNoteRequested,
  openSettings,
  previousView,
  type SearchLocation,
  type SearchType,
  type SettingsTab,
  searchColors,
  searchInput,
  searchLocations,
  searchQuery,
  searchTypes,
  selectedNotes,
  selectMode,
  settingsTab,
  showError,
  showSettings,
  showShortcuts,
  showSuccess,
  showWelcome,
  tagsShowActive,
  tagsShowArchived,
  tagsShowTrashed,
  toasts,
  toggleSearchColor,
  toggleSearchLocation,
  toggleSearchType,
  typeSearch,
} from "./ui.js";
export {
  allTags,
  canReorder,
  childTags,
  editingNote,
  filteredNotes,
  hiddenThrough,
  notesHiddenByTag,
  pinnedNotes,
  setTagColor,
  setTagHidden,
  sortedNotes,
  tagColorOf,
  tagCounts,
  unpinnedNotes,
} from "./views.js";
